// prettier-ignore

import {
  EvaArrowUpFill,
  IcOutlineDashboard,
  IcBaselineSearch,
  EvaArrowDownFill,
  IcOutlineSecurity,
  LineMdAlertCircle,
  LineMdBeerAltLoop,
  LineMdCircleTwotoneToConfirmCircleTransition,
  LineMdCloseCircle,
  LineMdEdit,
  LineMdMenu,
  LineMdMenuToCloseTransition,
  LineMdPauseToPlayFilledTransition,
  LineMdSunnyLoop,
  LineMdSunnyOutlineToMoonAltLoopTransition,
  MdiClose,
  MdiCircleOutline,
  MynauiComponents,
  MageSettings,
  PajamasStageAll,
  StashPackLight,
  SvgSpinners3DotsMove,
  SvgSpinnersBlocksShuffle3,
  HugeiconsPokemon,
  MdiPokeball,
  RiResetLeftFill,
  IcOutlineMale,
  IcOutlineFemale,
  TablerCards,
  LineMdMenuFoldLeft,
  LineMdMenuUnfoldLeft,
  IcOutlinePerson,
  IcOutlineSettings,
  IcOutlinePeople,
  IcOutlineLogout,
  IcOutlineAssessment,
  LineMdAlertTriangle,
  LineMdDocumentRemove,
  LineMdRotate270,
  IcOutlineHome,
  IcOutlineArrowBack,
  SvgSpinnersRingResize,
  SvgSpinners3DotsBounce,
  SvgSpinnersPulse3,
  LineMdCloudOffOutlineLoop,
  LineMdWifiOffOutline,
} from './svg-icons';
import { MappedIcons } from './types';

const mappedIcons: MappedIcons = {
  ['mdi:close']: MdiClose,
  ['mdi:circle-outline']: MdiCircleOutline,
  ['line-md:menu']: LineMdMenu,
  ['line-md:edit']: LineMdEdit,
  ['mdi:pokeball']: MdiPokeball,
  ['tabler:cards']: TablerCards,
  ['mage:settings']: MageSettings,
  ['ic:outline-male']: IcOutlineMale,
  ['stash:pack-light']: StashPackLight,
  ['eva:arrow-up-fill']: EvaArrowUpFill,
  ['pajamas:stage-all']: PajamasStageAll,
  ['ic:outline-female']: IcOutlineFemale,
  ['line-md:sunny-loop']: LineMdSunnyLoop,
  ['mynaui:components']: MynauiComponents,
  ['hugeicons:pokemon']: HugeiconsPokemon,
  ['ri:reset-left-fill']: RiResetLeftFill,
  ['ic:baseline-search']: IcBaselineSearch,
  ['eva:arrow-down-fill']: EvaArrowDownFill,
  ['ic:outline-security']: IcOutlineSecurity,
  ['line-md:close-circle']: LineMdCloseCircle,
  ['line-md:alert-circle']: LineMdAlertCircle,
  ['ic:outline-dashboard']: IcOutlineDashboard,
  ['line-md:beer-alt-loop']: LineMdBeerAltLoop,
  ['svg-spinners:3-dots-move']: SvgSpinners3DotsMove,
  ['svg-spinners:blocks-shuffle-3']: SvgSpinnersBlocksShuffle3,
  ['line-md:menu-to-close-transition']: LineMdMenuToCloseTransition,
  ['line-md:pause-to-play-filled-transition']:
    LineMdPauseToPlayFilledTransition,
  ['line-md:sunny-outline-to-moon-alt-loop-transition']:
    LineMdSunnyOutlineToMoonAltLoopTransition,
  ['line-md:circle-twotone-to-confirm-circle-transition']:
    LineMdCircleTwotoneToConfirmCircleTransition,
  ['line-md:menu-fold-left']: LineMdMenuFoldLeft,
  ['line-md:menu-unfold-left']: LineMdMenuUnfoldLeft,
  ['ic:outline-person']: IcOutlinePerson,
  ['ic:outline-settings']: IcOutlineSettings,
  ['ic:outline-people']: IcOutlinePeople,
  ['ic:outline-logout']: IcOutlineLogout,
  ['ic:outline-assessment']: IcOutlineAssessment,
  // Error and Status Icons
  ['line-md:alert-triangle']: LineMdAlertTriangle,
  ['line-md:document-remove']: LineMdDocumentRemove,
  ['line-md:rotate-270']: LineMdRotate270,
  ['ic:outline-home']: IcOutlineHome,
  ['ic:outline-arrow-back']: IcOutlineArrowBack,
  ['svg-spinners:ring-resize']: SvgSpinnersRingResize,
  ['svg-spinners:3-dots-bounce']: SvgSpinners3DotsBounce,
  ['svg-spinners:pulse-3']: SvgSpinnersPulse3,
  ['line-md:cloud-off-outline-loop']: LineMdCloudOffOutlineLoop,
  ['line-md:wifi-off-outline']: LineMdWifiOffOutline,
};

export default mappedIcons;
