// prettier-ignore

import {
  EvaArrowUpFill,
  IcOutlineDashboard,
  IcBaselineSearch,
  EvaArrowDownFill,
  IcOutlineSecurity,
  LineMdAlertCircle,
  LineMdBeerAltLoop,
  LineMdCircleTwotoneToConfirmCircleTransition,
  LineMdCloseCircle,
  LineMdEdit,
  LineMdMenu,
  LineMdMenuToCloseTransition,
  LineMdPauseToPlayFilledTransition,
  LineMdSunnyLoop,
  LineMdSunnyOutlineToMoonAltLoopTransition,
  MdiClose,
  MynauiComponents,
  MageSettings,
  PajamasStageAll,
  StashPackLight,
  SvgSpinners3DotsMove,
  SvgSpinnersBlocksShuffle3,
  HugeiconsPokemon,
  MdiPokeball,
  RiResetLeftFill,
  IcOutlineMale,
  IcOutlineFemale,
  TablerCards,
} from './SvgIcons';
import { MappedIcons } from './types';

const mappedIcons: MappedIcons = {
  ['mdi:close']: MdiClose,
  ['line-md:menu']: LineMdMenu,
  ['line-md:edit']: LineMdEdit,
  ['mdi:pokeball']: MdiPokeball,
  ['tabler:cards']: TablerCards,
  ['mage:settings']: MageSettings,
  ['ic:outline-male']: IcOutlineMale,
  ['stash:pack-light']: StashPackLight,
  ['eva:arrow-up-fill']: EvaArrowUpFill,
  ['pajamas:stage-all']: PajamasStageAll,
  ['ic:outline-female']: IcOutlineFemale,
  ['line-md:sunny-loop']: LineMdSunnyLoop,
  ['mynaui:components']: MynauiComponents,
  ['hugeicons:pokemon']: HugeiconsPokemon,
  ['ri:reset-left-fill']: RiResetLeftFill,
  ['ic:baseline-search']: IcBaselineSearch,
  ['eva:arrow-down-fill']: EvaArrowDownFill,
  ['ic:outline-security']: IcOutlineSecurity,
  ['line-md:close-circle']: LineMdCloseCircle,
  ['line-md:alert-circle']: LineMdAlertCircle,
  ['ic:outline-dashboard']: IcOutlineDashboard,
  ['line-md:beer-alt-loop']: LineMdBeerAltLoop,
  ['svg-spinners:3-dots-move']: SvgSpinners3DotsMove,
  ['svg-spinners:blocks-shuffle-3']: SvgSpinnersBlocksShuffle3,
  ['line-md:menu-to-close-transition']: LineMdMenuToCloseTransition,
  ['line-md:pause-to-play-filled-transition']: LineMdPauseToPlayFilledTransition,
  ['line-md:sunny-outline-to-moon-alt-loop-transition']: LineMdSunnyOutlineToMoonAltLoopTransition,
  ['line-md:circle-twotone-to-confirm-circle-transition']: LineMdCircleTwotoneToConfirmCircleTransition,
};

export default mappedIcons;
